### ISSUE TITLE
Replacing Outdated URLs

### ISSUE THREAD

**Issue by Aschmutz** [TGM-HIT/sew9-2324-worttrainer-fsylkaj#1]
Dear Mr. Sylkaj,
I noticed that you Software does not check if a URL actually still works. This is a problem as it does not show an Image for the Question and the User just gets asked for the word without knowing the Image. It would be great if you showed a Dialouge to Replace the Image URL.

This could be Implemented somewhat like this:
```java
public boolean checkURL(String urltext) {
        try {
            // Erstelle ein URL-Objekt aus der übergebenen Zeichenfolge
            URL url = new URL(urltext);
                          // Überprüfe, ob die URL syntaktisch korrekt ist
                          url.toURI();
               if(!isImage){
String newURL = JOptionPane.showMessageDialogue(/*ask for new URL*/);
                         checkURL(newURL)
}
return true;
        } catch (Exception e) {
            return false;
        }


        boolean isImage(String image_path){
            Image image = new ImageIcon(image_path).getImage();
            if(image.getWidth(null) == -1){
                 return false;
            }
            else{
                 return true;
            }
```

I'm not sure if the Code is Usable like that, but, that would be my idea.

Please fix it Quick,
with kind regards,
Leah Schmutz

**Comment by fsylkaj** [comment]
Thank you for your request. I am going to fix this problem! 

All the best, 
Florian Sylkaj

**Comment by fsylkaj** [comment]
Hello, 
I have edited my code according to your improvement tips. The issue that an image which is not available anymore is now fixed, by an additional check in the methode checkURL in the class Wortpaar. 

Thank you again for noticing this bug! 

All the best, 
Florian Sylkaj
